# Generated by Django 5.1.5 on 2025-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in the blog post URL', unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('past', 'Past')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exhibitions/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Main headline for the homepage', max_length=200)),
                ('intro_text', models.TextField(help_text='Welcome or about blurb')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sumup_link', models.URLField(help_text='Paste the SumUp payment link here')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
