# Generated by Django 5.1.5 on 2025-03-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_infopagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage_carousel/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Carousel Image',
                'verbose_name_plural': 'Homepage Carousel Images',
            },
        ),
        migrations.DeleteModel(
            name='HomepageContent',
        ),
    ]
